project_id = "frhxkbnicrbguxtvzzwx"

[functions.ussd]
verify_jwt = false

[functions.mpesa-callback]
verify_jwt = false

[functions.secure-login]
verify_jwt = false
[functions.revoke-token]
verify_jwt = false

[functions.change-password]
verify_jwt = false

verify_jwt = false
